------------------------------------------
# matrix in tenserflow
1. sizes (0,1,2,3,4)
2. dtype(bool,int16,...)
3. convert to new Type
---
#create new matrix in tenserflow
var = tf.constant(value,dtype)

---
# value in matrix tf =
1. 0_D => 4
2. 1_D => [4,9,4] => shape(3,)
3. 2_D => [[1,2],[2,4]] shape(2,2)
4. 3_D => ....
5. 4_D => ....
---
# data type

 [data type in tenserFlow like bool,int16,...](https://www.tensorflow.org/api_docs/python/tf/dtypes)
** Multiple data types are not allowed.**



---
# convert to new data type
 var = tf.cast(oldVar,dtype = tf.(newDataType)
# convert to tenser matrix


```
import numpy as np
npArray = np.array([2,5,6])
convert_tf = tf.convert_to_tensor(npArray)
print(npArray)
print(convert_tf)
```
# create identity matrix  
like this [ [1,0,0],
             [0,1,0], [0,0,1]]
```
tf.eye(
 num_rows = > size in 2-d ,
    num_columns=None if you want change in square matrix ,
    batch_shape=None if you need uper 2-d like 3-d =>([3,]) , 4-d =>[2,3,],
    dtype=tf.dtypes.float32, if you want change data type
    name=None)
```
# create  matrix filled with a same number
```
tf.fill(
    dims, value, name=None, layout=None
)
like this
tf.fill([2, 3], 9)
```
# create ones matrix

```
tf.ones(
    shape,
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
like this
ones_ones = tf.ones(
  [2,3,2]
  ,dtype = tf.int16
)
<!-- copy shape in any matrix  -->
tf.ones_like(
    input, dtype=None, name=None, layout=None
)
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.ones_like(tensor)

```
# create the zeros matrix
```
tf.zeros(
    shape,
    dtype=tf.dtypes.float32,
    name=None,
    layout=None
)
like this
zeroes_matrix = tf.zeros(
  [3,5,2],
  dtype= tf.int16)
```







In [49]:
import tensorflow as tf
zeros_mat = tf.zeros([2,3,2,3],dtype=tf.float32)
print(tf.shape(zeros_mat,))
print(zeros_mat)


tf.Tensor([2 3 2 3], shape=(4,), dtype=int32)
tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]]]], shape=(2, 3, 2, 3), dtype=float32)
